### ISSUE TITLE
Image missing from Derived copy published to Legacybeta

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#120]
I published a derived Page on beta.cnx.org. It was published on legacybeta.cnx.org, but it is missing the image.

Original 
http://beta.cnx.org/contents/3b8b507e-af4d-49e7-8d26-b1a61138a7fc/Ed's_Introduction
![screenshot from 2015-03-09 21 18 08](https://cloud.githubusercontent.com/assets/1394695/6568241/e2f4b4fc-c6a1-11e4-9581-aeaaa2aae7c5.png)

legacybeta version
http://legacybeta.cnx.org/content/m53215/latest/
![screenshot from 2015-03-09 21 19 26](https://cloud.githubusercontent.com/assets/1394695/6568245/ff00516a-c6a1-11e4-9480-9b265ce64151.png)

**Comment by pumazi** [comment]
The content shows a webview url for the image source, so the reference rewrite apparently never happened. This is an issue with the reference resolver, which is in cnx-archive.

**Comment by rich-hart** [comment]
I recently created my own derived copy of the same page on beta and the image rendered without any issues. http://beta.cnx.org/contents/22ef90de-46cf-4efc-adc5-fb06e2b041b1/richhart .

**Comment by amberwebb** [comment]
@rich-hart If I click on the link, I do not see the image. I am not logged in. If I log in, I can then see the image.

**Comment by karenc** [comment]
Wow this is really weird.  I clicked on the link just after seeing @amberwebb's comment...  And I'm logged in as amwebb.

**Comment by amberwebb** [comment]
What?????

**Comment by karenc** [comment]
![logged_in_as_amwebb](https://cloud.githubusercontent.com/assets/153353/6623993/69598caa-c8de-11e4-8116-2e4e35c06079.jpg)

**Comment by amberwebb** [comment]
I logged out right before you commented.

**Comment by karenc** [comment]
@rich-hart I thought it's the legacy site that's not working?  http://legacybeta.cnx.org/content/m53217/1.1?legacy=true has errors.

**Comment by rich-hart** [comment]
@karenc This seems to be an issue with the current instance of cnx-authoring running on dev.cnx.org (Connexions/cnx-authoring#205). When a page is being derived, the image resource hash string is being changed when it is sent to the editor. For example the image http://dev.cnx.org/resources/db2be0305f84bc13c2e3ff04639b8270 in the original page is being changed to http://dev.cnx.org/resources/68651684a49cebfde8ffc3f76a33a8184cdfdc63 in the derived page, the hash strings should be the same. This seems to only be a bug in dev at the moment because I've tested it on my own local instance and beta and the image rendered without any problems.  I didn't try it on legacybeta but i'll try it after lunch.

**Comment by rich-hart** [comment]
![wrong_login](https://cloud.githubusercontent.com/assets/2857670/6628012/15dc1060-c8d0-11e4-89da-c398945635c3.png)

**Comment by rich-hart** [comment]
Same thing happened to me too around Thu Mar 12 15:48:14 CDT 2015  (time stamp isn't exact) .

**Comment by rich-hart** [comment]
@reedstrm suggest's that the login issue is being cause by incorrect caching with varnish .

**Comment by reedstrm** [comment]
repository needed sha1 column populated. Works now.
